apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: nginx-sidecar
  name: nginx-sidecar
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: nginx-sidecar:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/slallemand/slallemand.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nginx-110-rhel7:latest
    type: Source
  triggers:
  - github:
      secret: ZIeqz4cusR8Xarc27e6U
    type: GitHub
  - generic:
      secret: 5dN_8M2QNIol2qL4SaLo
    type: Generic
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
status:
  lastVersion: 0
